// Code generated by goctl. DO NOT EDIT.

package appointments

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appointmentsFieldNames          = builder.RawFieldNames(&Appointments{})
	appointmentsRows                = strings.Join(appointmentsFieldNames, ",")
	appointmentsRowsExpectAutoSet   = strings.Join(stringx.Remove(appointmentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	appointmentsRowsWithPlaceHolder = strings.Join(stringx.Remove(appointmentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAppointmentsIdPrefix = "cache:appointments:id:"
)

type (
	appointmentsModel interface {
		Insert(ctx context.Context, data *Appointments) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Appointments, error)
		Update(ctx context.Context, data *Appointments) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAppointmentsModel struct {
		sqlc.CachedConn
		table string
	}

	Appointments struct {
		Id          int64          `db:"id"`
		PatientId   int64          `db:"patient_id"`   // 患者ID
		PatientName string         `db:"patient_name"` // 患者姓名
		Date        string         `db:"date"`         // 日期
		Time        string         `db:"time"`         // 时间
		Duration    string         `db:"duration"`     // 时长
		Type        string         `db:"type"`         // 类型
		Status      string         `db:"status"`       // 状态
		Notes       sql.NullString `db:"notes"`        // 备注
		UserId      string         `db:"user_id"`      // 用户ID
		IsDeleted   int64          `db:"is_deleted"`   // 是否删除
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
	}
)

func newAppointmentsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAppointmentsModel {
	return &defaultAppointmentsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`appointments`",
	}
}

func (m *defaultAppointmentsModel) Delete(ctx context.Context, id int64) error {
	appointmentsIdKey := fmt.Sprintf("%s%v", cacheAppointmentsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, appointmentsIdKey)
	return err
}

func (m *defaultAppointmentsModel) FindOne(ctx context.Context, id int64) (*Appointments, error) {
	appointmentsIdKey := fmt.Sprintf("%s%v", cacheAppointmentsIdPrefix, id)
	var resp Appointments
	err := m.QueryRowCtx(ctx, &resp, appointmentsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appointmentsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppointmentsModel) Insert(ctx context.Context, data *Appointments) (sql.Result, error) {
	appointmentsIdKey := fmt.Sprintf("%s%v", cacheAppointmentsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, appointmentsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PatientId, data.PatientName, data.Date, data.Time, data.Duration, data.Type, data.Status, data.Notes, data.UserId, data.IsDeleted)
	}, appointmentsIdKey)
	return ret, err
}

func (m *defaultAppointmentsModel) Update(ctx context.Context, data *Appointments) error {
	appointmentsIdKey := fmt.Sprintf("%s%v", cacheAppointmentsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, appointmentsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PatientId, data.PatientName, data.Date, data.Time, data.Duration, data.Type, data.Status, data.Notes, data.UserId, data.IsDeleted, data.Id)
	}, appointmentsIdKey)
	return err
}

func (m *defaultAppointmentsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAppointmentsIdPrefix, primary)
}

func (m *defaultAppointmentsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appointmentsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAppointmentsModel) tableName() string {
	return m.table
}
