CREATE TABLE IF NOT EXISTS patients (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `friendly_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '友好ID',
    `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '姓名',
    `age` INT NOT NULL DEFAULT 0 COMMENT '年龄',
    `gender` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '性别',
    `phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '手机号',
    `status` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '状态',
    `last_visit` TIMESTAMP NULL COMMENT '最后就诊时间',
    `avatar` TEXT COMMENT '头像',
    `history` TEXT COMMENT '病史',
    `allergies` TEXT COMMENT '过敏史',
    `note` TEXT COMMENT '备注',
    `attachments` TEXT COMMENT '附件',
    `details` TEXT COMMENT '详情',
    `user_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户ID',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_friendly_id` (`friendly_id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='患者表';